--------------------------------------------------------
--  文件已创建 - 星期四-六月-14-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SYS_USER_ROLE_ORGANIZATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SYS_USER_ROLE_ORGANIZATION" 
   (	"ID" NUMBER(*,0), 
	"SYS_USER_ID" NUMBER(*,0), 
	"SYS_ROLE_ORGANIZATION_ID" NUMBER(*,0), 
	"RANK" NUMBER(*,0) DEFAULT 0, 
	"CREATE_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6), 
	"CREATE_BY" NUMBER(*,0) DEFAULT 0, 
	"UPDATE_BY" NUMBER(*,0) DEFAULT 0, 
	"STATUS" NUMBER(*,0) DEFAULT 1, 
	"IS_FINAL" NUMBER(*,0) DEFAULT 1
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."SYS_USER_ROLE_ORGANIZATION"."ID" IS '主键id
';
 
   COMMENT ON COLUMN "SYSTEM"."SYS_USER_ROLE_ORGANIZATION"."RANK" IS '排序';
 
   COMMENT ON COLUMN "SYSTEM"."SYS_USER_ROLE_ORGANIZATION"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "SYSTEM"."SYS_USER_ROLE_ORGANIZATION"."UPDATE_TIME" IS '更新时间';
 
   COMMENT ON COLUMN "SYSTEM"."SYS_USER_ROLE_ORGANIZATION"."CREATE_BY" IS '创建人id';
 
   COMMENT ON COLUMN "SYSTEM"."SYS_USER_ROLE_ORGANIZATION"."UPDATE_BY" IS '更新人id';
 
   COMMENT ON COLUMN "SYSTEM"."SYS_USER_ROLE_ORGANIZATION"."STATUS" IS '数据状态,1:正常,2:删除';
 
   COMMENT ON COLUMN "SYSTEM"."SYS_USER_ROLE_ORGANIZATION"."IS_FINAL" IS '是否能修改';
REM INSERTING into SYSTEM.SYS_USER_ROLE_ORGANIZATION
SET DEFINE OFF;
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (3226,2,2,0,null,null,0,0,1,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (2310,2,1,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (2322,2906,3,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (2635,2591,4,0,null,null,0,0,1,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (2355,5528,4,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (2849,758,5,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (2775,5528,3,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (2839,1,2,0,null,null,0,0,1,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (2872,758,1,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (3190,2906,3,0,null,null,0,0,1,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (3197,2,3,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (3203,2,3,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (3206,2,4,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (3210,758,3,0,null,null,0,0,1,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (3214,2,2,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (3223,2,2,0,null,null,0,0,2,1);
Insert into SYSTEM.SYS_USER_ROLE_ORGANIZATION (ID,SYS_USER_ID,SYS_ROLE_ORGANIZATION_ID,RANK,CREATE_TIME,UPDATE_TIME,CREATE_BY,UPDATE_BY,STATUS,IS_FINAL) values (3226,2,2,0,null,null,0,0,1,1);
--------------------------------------------------------
--  Constraints for Table SYS_USER_ROLE_ORGANIZATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SYS_USER_ROLE_ORGANIZATION" MODIFY ("ID" NOT NULL ENABLE);
